### ISSUE TITLE
Header record does not exist or is empty at offset: '0'

### ISSUE THREAD

**Issue by tfk-kaare** [TromsFylkestrafikk/ragnarok-consat#17]
```
The header record does not exist or is empty at offset: `0`
Occured in /home/kaare/src/ragnarok/vendor/league/csv/src/SyntaxError.php(44)
- ...
- #5 /home/kaare/src/ragnarok/vendor/league/csv/src/Reader.php(322): League\Csv\Reader->getRecords()
- #6 /home/kaare/src/ragnarok/vendor/ragnarok/sink/src/Services/CsvToTable.php(226): League\Csv\Reader->getIterator()
- #7 /home/kaare/src/ragnarok-consat/src/Services/ConsatImporter.php(42): Ragnarok\Sink\Services\CsvToTable->exec()
- #8 /home/kaare/src/ragnarok-consat/src/Sinks/SinkConsat.php(60): Ragnarok\Consat\Services\ConsatImporter->import() 
```

**Comment by tfk-kaare** [comment]
This is caused by empty (almost) InvalidatedJourneys.csv files. No headers, no content.

**Comment by tfk-kaare** [comment]
One PR should not close this. *All* PRs should.

**Comment by tfk-kaare** [comment]
Fixed!
